linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple

linters-settings:
  goimports:
    local-prefixes: github.com/githonllc/entdomain

issues:
  exclude-dirs:
    - templates
